### ISSUE TITLE
Datatypes in columns

### ISSUE THREAD

**Issue by wood-chris** [d2rq/d2rq#270]
Hello,

I'm still fairly new to D2RQ, but have been mapping a schema from a small set of Oracle tables.  I have a foreign key that I've got specified in a PropertyBridge:

```
...
d2rq:refersToClassMap map:MyTestTable1;
d2rq:join "MyTestTable1.ColumnX => MyTestTable2.ColumnY";
```

The FK is constrained correctly, and has a DataType of `varchar(8 BYTE)`. For testing purposes, if I carry out the following in Oracle:

```
UPDATE MyTestTable1 SET ColumnX='A1';
UPDATE MyTestTable2 SET ColumnY='A1';
```

then the property/value pair at `http://localhost:2020/page/MyTestTable1/1` shows:

```
vocab:MyTestTable1_ColumnX  MyTestTable2:A1
```

If I then run (without changing _anything_ else):

```
UPDATE MyTestTable1 SET ColumnX='10';
UPDATE MyTestTable2 SET ColumnY='10';
```

then the property/value pair at `http://localhost:2020/page/MyTestTable1/1` becomes:

```
vocab:MyTestTable1_ColumnX  <http://localhost:2020/resource/MyTestTable2/10>
```

i.e. even though the column type is still a `varchar2`, `D2RQ` changes its behaviour based on it being a true mixed `varchar2` or just a numerical value.  Is this expected? Have I missed something in the docs about this?!

Thanks,
Chris

**Comment by cygri** [comment]
In Turtle syntax, `MyTestTable2:A1` and `<http://localhost:2020/resource/MyTestTable2/A1>` are equivalent (assuming the proper `@prefix` declaration at the top of the file). It's just two different ways of writing exactly the same URI. The former is just syntactic sugar for the latter.

The local part of a prefixed name (that is, the `A1` part in `MyTestTable2:A1`) must not start with a digit, so that's why D2RQ doesn't use the prefixed name syntax but the full `<...>` syntax in the second case.

None of this is specific to D2RQ, this is just basic Turtle syntax. FWIW, if you specified output in N-Triples syntax, you would get exactly the same result in both cases because N-Triples doesn't have syntactic sugar such as prefixed names.
