### ISSUE TITLE
Relationship defined in a table

### ISSUE THREAD

**Issue by marco-brandizi** [d2rq/d2rq#274]
I hope this is the right place where to ask this question.

I have a table of equivalent URIs, something like mappings ( uri1, uri2 ), which I'd like to translate onto $uri1 owl:sameAs $uri2. I've also a table like entity ( uri, title, description ), which I'd like to map to something like: 

  $uri a ex:Entity; dcterms:title $title; dcterms:description $description

(URIs are the same found in mappings).

What is the best strategy to do that? I am confused, because there is no RDF class that is instance of records in mappings, in fact this is only a join table.

Thanks in advance,
Marco.

**Comment by cygri** [comment]
Mapping the `entity` table is straightforward, just use `d2rq:uriColumn` in the class map instead of the more typical `d2rq:uriPattern`.

For the `mappings` table, create a separate class map _without_ a `d2rq:class` value, and a single property bridge with property `owl:sameAs`. Both the class map and the property bridge should have a `d2rq:uriColumn`, with `mappings.uri1` and `mappings.uri2` as the value, respectively.

(Class maps don't actually need a class at all. You can think of a class map simply as a rule for creating URIs from the database. Optionally, you may add an `rdf:type` to all these URIs, using `d2rq:class`. And then you may add property bridges to generate more triples that use these URIs as the subject, and maybe inverse property bridges that use these URIs as object.)

Please re-open if you need further help.

**Comment by marco-brandizi** [comment]
Yeeeaahh! It works! Thanks a lot for the very quick reply!
