### ISSUE TITLE
Create mapping file based on specific ontology

### ISSUE THREAD

**Issue by ghilan20** [d2rq/d2rq#295]
I'm beginner in d2rq and i use it in order to access my database and create mapping file with a default configuration that work really good, but now i want to create the mapping file based on my special ontology such as ( iot-lite or others ), how i configure the d2r server to get that.
Pleas helping

**Comment by cygri** [comment]
Typically one starts by generating a default mapping file, and then edits that file in a text editor, to use classes and properties from the desired ontology, instead of the auto-generated term in the `vocab:` namespace.

The mapping files are in Turtle syntax. One needs to know the basics of Turtle to be able to edit a mapping file.

The D2RQ mapping file format is explained here:
http://d2rq.org/d2rq-language

Please re-open the issue if you have further questions.

**Comment by ghilan20** [comment]
Thank you for the clarification.
I will edit it with text editor as you mentioned above.
