### ISSUE TITLE
Mapping a propertybirdge into an ontology class

### ISSUE THREAD

**Issue by MarcyRouge** [d2rq/d2rq#327]
hello, 

I would like to know if there is a way of mapping a propertybridge to a class. 
In other words, some columns of the database are represented as classes in my ontology. Therefore, I would need to take those propertybridges and somehow map them as a class, that does not extist in the data base. 

I have looked in the documentation but I can not find anything that helps me to do that.

Thank you in advance,
Marcela

**Comment by cygri** [comment]
Not sure I understand. Can you give an example?

**Comment by MarcyRouge** [comment]
Hello, thanks for your answer. 

Let's say I have in my Database a table called "Conference" with three attributes : name, date, coordinator. 
My ontology has instead a class called  "Conference" and another called "Coordinator". 

By following the exemple document, I can easily mapp the classmap conference to the ontology class. 
map:Conference a d2rq:ClassMap;
	d2rq:dataStorage map:database;
       d2rq:class myOntology:Conference ;

and the propertybrides to map as properties would be name, date and coordinator. 
map:name a d2rq:PropertyBridge;
	d2rq:belongsToClassMap map:Conference;
       d2rq:property ....
map:date a d2rq:PropertyBridge;
	d2rq:belongsToClassMap map:Conference;
       d2rq:property ....
map:coordinator a d2rq:PropertyBridge;
	d2rq:belongsToClassMap map:Conference;
        d2rq:property ....

However, I don't want to map coordinator as a property but as a class instead. How can I do it, if coordinator does not exist as a table in my database? 

I hope this exemple is clear. Otherwise I will try to reformulate it. 

Thanks again

**Comment by cygri** [comment]
Thanks for those details, I think I understand now.

Make a class map for your Coordinator class. Its URI pattern should be based on the `Conference.coordinator` column (with an encoding of your choice, see [here](http://d2rq.org/d2rq-language#dfn-uri-pattern)). The property bridge for the coordinator property should then refer to the Coordinator class map. No join is needed because both class maps are based on the same table.

I'll close this issue but feel free to reopen if this doesn't solve your problem.
